spring:
  datasource:  # mysql 사용
    url: jdbc:h2:tcp://localhost/~/ditto
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      connection-test-query: select 1 from dual
  jpa:  # jpa 사용시 추가
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          show_sql: true
          format_sql: true
      open-in-view: false
      h2:
        console:
          enabled: true
    defer-datasource-initialization: true #더미데이터 용
    show-sql: true
  sql: #더미데이터 용
    init:
      mode: always
      data-locations: classpath:data.sql
      encoding: UTF-8
  data:
    redis:
      host: localhost
      port: 6379